import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SearchProvider } from './contexts/search'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Combate de heróis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SearchProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
      </SearchProvider>
  )
}
